[Sup 1959]Fix Identation issue, add enabling RBAC token step, update task metadata
jarretlavallee/puppet-deploy_pe pull request #25
Opened 2021-05-08 06:36 UTC by henrywangpuppet

2021-05-10 13:11 UTC, jarretlavallee requested changes
Overall this looks good. I have a couple changes that I would like to see to make it more resilient and flexible.

2021-05-10 13:11 UTC, jarretlavallee commented on tasks/provision_newstyle_compiler.sh
> +/bin/curl -X POST -H 'Content-Type: application/json' --cacert $(${PUPPET_BIN}/puppet config print cacert) https://$(${PUPPET_BIN}/puppet config print server):4433/rbac-api/v1/auth/token -d '{"login"
This needs some error checking. Please also pass in the password as a parameter since it can be changed.

2021-05-11 08:48 UTC, henrywangpuppet commented
Updated the codes already

2021-05-11 13:07 UTC, jarretlavallee commented
Looks good. Let's update the reference.md. 

```
gem install puppet-strings
puppet strings generate 
```

2021-05-11 14:46 UTC, merged